# Streamlit Configuration File
# This file contains app-wide configuration settings for your Streamlit application
# Place this file in the .streamlit/ directory in your project root

[global]
# Set to false to disable the ability to run arbitrary Python code via the Streamlit interface
developmentMode = false

# If true, will show a warning when you run a Streamlit script without
# passing in command line arguments.
showWarningOnDirectExecution = true

# Level of logging: 'error', 'warning', 'info', or 'debug'.
logLevel = "info"

# If true, will show the deprecation warnings
showDeprecationWarnings = true

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

# String format for logging messages. If logger.datetimeFormat is set, logger messages
# will default to `%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s`.
# See [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects)
# for available attributes.
messageFormat = "%(asctime)s %(message)s"

[client]
# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not connect to the Streamlit backend.
# This is useful for testing.
showErrorDetails = true

[browser]
# Internet address where users should point their browsers in order to connect to the app.
# Can be IP address or DNS name and path.
# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Default: 'localhost'
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

# Port where users should point their browsers in order to connect to the app.
# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Default: whatever value is set in server.port.
serverPort = 8501

[mapbox]
# Configure Mapbox token for st.pydeck_chart and st.map.
# token = "your_mapbox_token_here"

[deprecation]
# Set to false to disable the deprecation warning for the file uploader encoding.
showfileUploaderEncoding = true

# Set to false to disable the deprecation warning for using the global pyplot instance.
showPyplotGlobalUse = true

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#FF6B6B"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"

[server]
# List of folders that should not be watched for changes. This impacts both "Run on Save" and @st.cache.
# Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
# Allowed values: * "auto" : Streamlit will attempt to use the watchdog module, and
#                   falls back to polling if watchdog is not available.
#                 * "watchdog" : Force Streamlit to use the watchdog module.
#                 * "poll" : Force Streamlit to always use polling.
#                 * "none" : Streamlit will not watch files.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should
# be set to the same value across all replicas to ensure they all share the same secret.
# Default: randomly generated secret key.
# cookieSecret = "your-secret-key-here"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address where the server will listen for client and browser connections.
# Use this if you want to bind the server to a specific address.
# If set, the server will only be accessible from this address, and not from any other address.
address = "localhost"

# The port where the server will listen for client and browser connections.
port = 8501

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for added security.
# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is on and
# `server.enableCORS` is off at the same time, we will prioritize `server.enableXsrfProtection`.
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is on and
# `server.enableCORS` is off at the same time, we will prioritize `server.enableXsrfProtection`.
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

# Enable serving files from a `static` directory in the running app's directory.
enableStaticServing = false

# Server certificate file for connecting via HTTPS.
# Must be set at the same time as "server.sslKeyFile".
# ['DO NOT COMMIT CERTIFICATES TO A PUBLIC REPOSITORY']
# sslCertFile =

# Cryptographic key file for connecting via HTTPS.
# Must be set at the same time as "server.sslCertFile".
# ['DO NOT COMMIT CERTIFICATES TO A PUBLIC REPOSITORY']
# sslKeyFile =
